export const dataTable = "\\!\n" +
    "\"\\,\"\n" +
    "\\:\n" +
    "\\>\n" +
    "\\;\n" +
    "\\#\n" +
    "\\$\n" +
    "\\%\n" +
    "\\&\n" +
    "\\\\\n" +
    "\\_\n" +
    "\\{ \\}\n" +
    "\\|\n" +
    "\\above\n" +
    "\\abovewithdelims\n" +
    "\\acute\n" +
    "\\aleph\n" +
    "\\alpha\n" +
    "\\amalg\n" +
    "\\And\n" +
    "\\angle\n" +
    "\\approx\n" +
    "\\approxeq\n" +
    "\\arccos\n" +
    "\\arcsin\n" +
    "\\arctan\n" +
    "\\arg\n" +
    "\\array\n" +
    "\\arrowvert\n" +
    "\\Arrowvert\n" +
    "\\ast\n" +
    "\\asymp\n" +
    "\\atop\n" +
    "\\atopwithdelims\n" +
    "\\backepsilon\n" +
    "\\backprime\n" +
    "\\backsim\n" +
    "\\backsimeq\n" +
    "\\backslash\n" +
    "\\bar\n" +
    "\\barwedge\n" +
    "\\Bbb\n" +
    "\\Bbbk\n" +
    "\\because\n" +
    "\\begin\n" +
    "\\beta\n" +
    "\\beth\n" +
    "\\between\n" +
    "\\bf\n" +
    "\\Bigg\n" +
    "\\bigg\n" +
    "\\Big\n" +
    "\\big\n" +
    "\\Biggl \\Biggm \\Biggr\n" +
    "\\biggl \\biggm \\biggr\n" +
    "\\Bigl \\Bigm \\Bigl\n" +
    "\\bigl \\bigm \\bigr\n" +
    "\\bigcap\n" +
    "\\bigcirc\n" +
    "\\bigcup\n" +
    "\\bigodot\n" +
    "\\bigoplus\n" +
    "\\bigotimes\n" +
    "\\bigsqcup\n" +
    "\\bigstar\n" +
    "\\bigtriangledown\n" +
    "\\bigtriangleup\n" +
    "\\biguplus\n" +
    "\\bigvee\n" +
    "\\bigwedge\n" +
    "\\binom\n" +
    "\\blacklozenge\n" +
    "\\blacksquare\n" +
    "\\blacktriangle\n" +
    "\\blacktriangledown\n" +
    "both AMSsymbols\n" +
    "\\blacktriangleleft\n" +
    "\\blacktriangleright\n" +
    "both AMSsymbols\n" +
    "\\bmod\n" +
    "\\boldsymbol\n" +
    "\\bot\n" +
    "\\bowtie\n" +
    "\\Box\n" +
    "\\boxdot\n" +
    "\\boxed\n" +
    "\\boxminus\n" +
    "\\boxplus\n" +
    "\\boxtimes\n" +
    "\\brace\n" +
    "\\bracevert\n" +
    "\\brack\n" +
    "\\breve\n" +
    "\\buildrel ... \\over ...\n" +
    "\\bullet\n" +
    "\\Bumpeq\n" +
    "\\bumpeq\n" +
    "\\cal\n" +
    "\\cancel\n" +
    "\\Cap\n" +
    "\\cap\n" +
    "\\cases\n" +
    "\\cdot\n" +
    "\\cdotp\n" +
    "\\cdots\n" +
    "\\centerdot\n" +
    "\\cfrac\n" +
    "\\check\n" +
    "\\checkmark\n" +
    "\\chi\n" +
    "\\choose\n" +
    "\\circ\n" +
    "\\circeq\n" +
    "\\circlearrowleft\n" +
    "\\circlearrowright\n" +
    "\\circledast\n" +
    "\\circledcirc\n" +
    "\\circleddash\n" +
    "\\circledR\n" +
    "\\circledS\n" +
    "\\class\n" +
    "\\clubsuit\n" +
    "\\colon\n" +
    "\\color\n" +
    "\\complement\n" +
    "\\cong\n" +
    "\\coprod\n" +
    "\\cos\n" +
    "\\cosh\n" +
    "\\cot\n" +
    "\\coth\n" +
    "\\cr\n" +
    "\\csc\n" +
    "\\cssId\n" +
    "\\Cup\n" +
    "\\cup\n" +
    "\\curlyeqprec\n" +
    "\\curlyeqsucc\n" +
    "\\curlyvee\n" +
    "\\curlywedge\n" +
    "\\curvearrowleft\n" +
    "\\curvearrowright\n" +
    "\\dagger\n" +
    "\\ddagger\n" +
    "\\daleth\n" +
    "\\dashleftarrow\n" +
    "\\dashrightarrow\n" +
    "\\dashv\n" +
    "\\dbinom\n" +
    "\\dot\n" +
    "\\ddot\n" +
    "\\dddot\n" +
    "\\ddddot\n" +
    "\\ddots\n" +
    "\\DeclareMathOperator\n" +
    "\\def\n" +
    "\\deg\n" +
    "\\Delta\n" +
    "\\delta\n" +
    "\\det\n" +
    "\\dfrac\n" +
    "\\diagdown\n" +
    "\\diagup\n" +
    "\\Diamond\n" +
    "\\diamond\n" +
    "\\diamondsuit\n" +
    "\\digamma\n" +
    "\\dim\n" +
    "\\displaylines\n" +
    "\\displaystyle\n" +
    "\\div\n" +
    "\\divideontimes\n" +
    "\\Doteq\n" +
    "\\doteq\n" +
    "\\dotplus\n" +
    "\\dots\n" +
    "\\dotsb\n" +
    "\\dotsc\n" +
    "\\dotsi\n" +
    "\\dotsm\n" +
    "\\dotso\n" +
    "\\doublebarwedge\n" +
    "\\doublecap\n" +
    "\\doublecup\n" +
    "\\downarrow\n" +
    "\\Downarrow\n" +
    "\\downdownarrows\n" +
    "\\downharpoonleft\n" +
    "\\downharpoonright\n" +
    "\\ell\n" +
    "\\emptyset\n" +
    "\\end\n" +
    "\\enspace\n" +
    "\\epsilon\n" +
    "\\eqalign\n" +
    "\\eqalignno\n" +
    "\\eqcirc\n" +
    "\\eqsim\n" +
    "\\eqslantgtr\n" +
    "\\eqslantless\n" +
    "\\equiv\n" +
    "Error Messages;\n" +
    "page processing log\n" +
    "\\eta\n" +
    "\\eth\n" +
    "\\exists\n" +
    "\\exp\n" +
    "\\fallingdotseq\n" +
    "\\fbox\n" +
    "\\Finv\n" +
    "\\flat\n" +
    "\\forall\n" +
    "\\frac\n" +
    "\\frak\n" +
    "\\frown\n" +
    "\\Game\n" +
    "\\Gamma\n" +
    "\\gamma\n" +
    "\\gcd\n" +
    "\\ge\n" +
    "\\geq\n" +
    "\\geqq\n" +
    "\\geqslant\n" +
    "\\genfrac\n" +
    "\\gets\n" +
    "\\gg\n" +
    "\\ggg\n" +
    "\\gggtr\n" +
    "\\gimel\n" +
    "\\gtrapprox\n" +
    "\\gnapprox\n" +
    "\\gneq\n" +
    "\\gneqq\n" +
    "\\gvertneqq\n" +
    "\\gtrsim\n" +
    "\\gnsim\n" +
    "\\grave\n" +
    "\\gt\n" +
    "\\gtrdot\n" +
    "\\gtreqless\n" +
    "\\gtreqqless\n" +
    "\\gtrless\n" +
    "\\hat\n" +
    "\\hbar\n" +
    "\\hbox\n" +
    "\\hdashline\n" +
    "\\hline\n" +
    "\\heartsuit\n" +
    "\\hfil\n" +
    "\\hfill\n" +
    "\\hom\n" +
    "\\hookleftarrow\n" +
    "\\hookrightarrow\n" +
    "\\hphantom\n" +
    "\\href\n" +
    "\\hskip\n" +
    "\\hslash\n" +
    "\\hspace\n" +
    "\\Huge\n" +
    "\\huge\n" +
    "\\iddots\n" +
    "\\idotsint\n" +
    "\\iff\n" +
    "\\iiiint\n" +
    "\\iiint\n" +
    "\\iint\n" +
    "\\int\n" +
    "\\intop\n" +
    "\\Im\n" +
    "\\imath\n" +
    "\\impliedby\n" +
    "\\implies\n" +
    "\\in\n" +
    "\\inf\n" +
    "\\infty\n" +
    "\\injlim\n" +
    "\\intercal\n" +
    "\\iota\n" +
    "\\it\n" +
    "\\jmath\n" +
    "\\Join\n" +
    "\\kappa\n" +
    "\\ker\n" +
    "\\kern\n" +
    "\\Lambda\n" +
    "\\lambda\n" +
    "\\land\n" +
    "\\langle\n" +
    "\\LARGE\n" +
    "\\Large\n" +
    "\\large\n" +
    "\\LaTeX\n" +
    "\\lbrace\n" +
    "\\lbrack\n" +
    "\\lceil\n" +
    "\\ldotp\n" +
    "\\ldots\n" +
    "\\le\n" +
    "\\leq\n" +
    "\\leqq\n" +
    "\\leqslant\n" +
    "\\leadsto\n" +
    "\\left\n" +
    "\\leftarrow\n" +
    "\\Leftarrow\n" +
    "\\leftarrowtail\n" +
    "\\leftharpoondown\n" +
    "\\leftharpoonup\n" +
    "\\leftleftarrows\n" +
    "\\leftrightarrow\n" +
    "\\Leftrightarrow\n" +
    "\\leftrightarrows\n" +
    "\\leftrightharpoons\n" +
    "\\leftrightsquigarrow\n" +
    "\\leftroot\n" +
    "\\leftthreetimes\n" +
    "\\leqalignno\n" +
    "\\lessapprox\n" +
    "\\lessdot\n" +
    "\\lesseqgtr\n" +
    "\\lesseqqgtr\n" +
    "\\lessgtr\n" +
    "\\lesssim\n" +
    "\\lfloor\n" +
    "\\lg\n" +
    "\\lgroup\n" +
    "\\lhd\n" +
    "\\lim\n" +
    "\\liminf\n" +
    "\\limits\n" +
    "\\limsup\n" +
    "\\ll\n" +
    "\\llap\n" +
    "\\llcorner\n" +
    "\\lrcorner\n" +
    "\\Lleftarrow\n" +
    "\\lll\n" +
    "\\llless\n" +
    "\\lmoustache\n" +
    "\\ln\n" +
    "\\lnapprox\n" +
    "\\lneq\n" +
    "\\lneqq\n" +
    "\\lnot\n" +
    "\\lnsim\n" +
    "\\log\n" +
    "\\longleftarrow\n" +
    "\\Longleftarrow\n" +
    "\\longrightarrow\n" +
    "\\Longrightarrow\n" +
    "\\longleftrightarrow\n" +
    "\\Longleftrightarrow\n" +
    "\\longmapsto\n" +
    "\\looparrowleft\n" +
    "\\looparrowright\n" +
    "\\lor\n" +
    "\\lower\n" +
    "\\lozenge\n" +
    "\\Lsh\n" +
    "\\lt\n" +
    "\\ltimes\n" +
    "\\lvert\n" +
    "\\lVert\n" +
    "\\lvertneqq\n" +
    "\\maltese\n" +
    "\\mapsto\n" +
    "\\mathbb\n" +
    "\\mathbf\n" +
    "\\mathbin\n" +
    "\\mathcal\n" +
    "\\mathchoice\n" +
    "\\mathclose\n" +
    "\\mathfrak\n" +
    "\\mathinner\n" +
    "\\mathit\n" +
    "\\mathop\n" +
    "\\mathopen\n" +
    "\\mathord\n" +
    "\\mathpunct\n" +
    "\\mathrel\n" +
    "\\mathring\n" +
    "\\mathrm\n" +
    "\\mathscr\n" +
    "\\mathsf\n" +
    "\\mathstrut\n" +
    "\\mathtt\n" +
    "\\matrix\n" +
    "\\max\n" +
    "\\mbox\n" +
    "\\measuredangle\n" +
    "\\mho\n" +
    "\\mid\n" +
    "\\min\n" +
    "\\mit\n" +
    "\\mod\n" +
    "\\models\n" +
    "\\moveleft\n" +
    "\\moveright\n" +
    "\\mp\n" +
    "\\mskip\n" +
    "\\mspace\n" +
    "\\mu\n" +
    "\\multimap\n" +
    "\\nabla\n" +
    "\\natural\n" +
    "\\ncong\n" +
    "\\ne\n" +
    "\\nearrow\n" +
    "\\neg\n" +
    "\\negthinspace\n" +
    "\\negmedspace\n" +
    "\\negthickspace\n" +
    "\\neq\n" +
    "\\newcommand\n" +
    "\\newenvironment\n" +
    "\\newline\n" +
    "\\nexists\n" +
    "\\ngeq\n" +
    "\\ngeqq\n" +
    "\\ngeqslant\n" +
    "\\ngtr\n" +
    "\\ni\n" +
    "\\nleftarrow\n" +
    "\\nLeftarrow\n" +
    "\\nleftrightarrow\n" +
    "\\nLeftrightarrow\n" +
    "\\nleq\n" +
    "\\nleqq\n" +
    "\\nleqslant\n" +
    "\\nless\n" +
    "\\nmid\n" +
    "\\nobreakspace\n" +
    "\\nolimits\n" +
    "\\normalsize\n" +
    "\\not\n" +
    "\\notag\n" +
    "\\notin\n" +
    "\\nparallel\n" +
    "\\nprec\n" +
    "\\npreceq\n" +
    "\\nrightarrow\n" +
    "\\nRightarrow\n" +
    "\\nshortmid\n" +
    "\\nshortparallel\n" +
    "\\nsim\n" +
    "\\nsubseteq\n" +
    "\\nsubseteqq\n" +
    "\\nsucc\n" +
    "\\nsucceq\n" +
    "\\nsupseteq\n" +
    "\\nsupseteqq\n" +
    "\\ntriangleleft\n" +
    "\\ntrianglelefteq\n" +
    "\\ntriangleright\n" +
    "\\ntrianglerighteq\n" +
    "\\nu\n" +
    "\\nVDash\n" +
    "\\nVdash\n" +
    "\\nvDash\n" +
    "\\nvdash\n" +
    "\\nwarrow\n" +
    "\\odot\n" +
    "\\ominus\n" +
    "\\oplus\n" +
    "\\oslash\n" +
    "\\otimes\n" +
    "\\oint\n" +
    "\\oldstyle\n" +
    "\\omega\n" +
    "\\Omega\n" +
    "\\omicron\n" +
    "\\operatorname\n" +
    "\\over\n" +
    "\\overbrace\n" +
    "\\overleftarrow\n" +
    "\\overrightarrow\n" +
    "\\overleftrightarrow\n" +
    "\\overline\n" +
    "\\overparen\n" +
    "\\overset\n" +
    "\\overwithdelims\n" +
    "\\owns\n" +
    "\\parallel\n" +
    "\\partial\n" +
    "\\perp\n" +
    "\\phantom\n" +
    "\\phi\n" +
    "\\Phi\n" +
    "\\pi\n" +
    "\\Pi\n" +
    "\\pitchfork\n" +
    "\\pm\n" +
    "\\pmatrix\n" +
    "\\pmb\n" +
    "\\pmod\n" +
    "\\pod\n" +
    "\\Pr\n" +
    "\\prec\n" +
    "\\precapprox\n" +
    "\\precnapprox\n" +
    "\\preccurlyeq\n" +
    "\\preceq\n" +
    "\\precneqq\n" +
    "\\precsim\n" +
    "\\precnsim\n" +
    "\\prime\n" +
    "\\prod\n" +
    "\\projlim\n" +
    "\\propto\n" +
    "\\psi\n" +
    "\\Psi\n" +
    "\\quad\n" +
    "\\qquad\n" +
    "\\raise\n" +
    "\\rangle\n" +
    "\\rbrace\n" +
    "\\rbrack\n" +
    "\\rceil\n" +
    "\\Re\n" +
    "\\renewcommand\n" +
    "\\require (non-standard)\n" +
    "\\restriction\n" +
    "\\rfloor\n" +
    "\\rgroup\n" +
    "\\rhd\n" +
    "\\rho\n" +
    "\\right\n" +
    "\\rightarrow\n" +
    "\\Rightarrow\n" +
    "\\rightarrowtail\n" +
    "\\rightharpoondown\n" +
    "\\rightharpoonup\n" +
    "\\rightleftarrows\n" +
    "\\rightleftharpoons\n" +
    "\\rightrightarrows\n" +
    "\\rightsquigarrow\n" +
    "\\rightthreetimes\n" +
    "\\risingdotseq\n" +
    "\\rlap\n" +
    "\\rm\n" +
    "\\rmoustache\n" +
    "\\root ... \\of\n" +
    "\\Rrightarrow\n" +
    "\\Rsh\n" +
    "\\rtimes\n" +
    "\\Rule (non-standard)\n" +
    "\\rvert\n" +
    "\\rVert\n" +
    "\\S\n" +
    "\\scr\n" +
    "\\scriptscriptstyle\n" +
    "\\scriptsize\n" +
    "\\scriptstyle\n" +
    "\\searrow\n" +
    "\\sec\n" +
    "\\setminus\n" +
    "\\sf\n" +
    "\\sharp\n" +
    "\\shortmid\n" +
    "\\shortparallel\n" +
    "\\shoveleft\n" +
    "\\shoveright\n" +
    "\\sideset\n" +
    "\\sigma\n" +
    "\\Sigma\n" +
    "\\sim\n" +
    "\\simeq\n" +
    "\\sin\n" +
    "\\sinh\n" +
    "\\skew\n" +
    "\\small\n" +
    "\\smallfrown\n" +
    "\\smallint\n" +
    "\\smallsetminus\n" +
    "\\smallsmile\n" +
    "\\smash\n" +
    "\\smile\n" +
    "\\space\n" +
    "\\Space (non-standard)\n" +
    "\\spadesuit\n" +
    "\\sphericalangle\n" +
    "\\sqcap\n" +
    "\\sqcup\n" +
    "\\sqrt\n" +
    "\\sqsubset\n" +
    "\\sqsupset\n" +
    "\\sqsubseteq\n" +
    "\\sqsupseteq\n" +
    "\\square\n" +
    "\\stackrel\n" +
    "\\star\n" +
    "\\strut\n" +
    "\\style\n" +
    "\\subset\n" +
    "\\Subset\n" +
    "\\subseteq\n" +
    "\\subsetneq\n" +
    "\\subseteqq\n" +
    "\\subsetneqq\n" +
    "\\substack\n" +
    "\\succ\n" +
    "\\succapprox\n" +
    "\\succnapprox\n" +
    "\\succcurlyeq\n" +
    "\\succeq\n" +
    "\\succneqq\n" +
    "\\succsim\n" +
    "\\succnsim\n" +
    "\\sum\n" +
    "\\sup\n" +
    "\\supset\n" +
    "\\Supset\n" +
    "\\supseteq\n" +
    "\\supsetneq\n" +
    "\\supseteqq\n" +
    "\\supsetneqq\n" +
    "\\surd\n" +
    "\\swarrow\n" +
    "\\tag\n" +
    "\\tan\n" +
    "\\tanh\n" +
    "\\tau\n" +
    "\\tbinom\n" +
    "\\TeX\n" +
    "\\text\n" +
    "\\textbf\n" +
    "\\textit\n" +
    "\\textrm\n" +
    "\\textsf\n" +
    "\\texttt\n" +
    "\\textstyle\n" +
    "\\tfrac\n" +
    "\\therefore\n" +
    "\\theta\n" +
    "\\Theta\n" +
    "\\thickapprox\n" +
    "\\thicksim\n" +
    "\\thinspace\n" +
    "\\tilde\n" +
    "\\times\n" +
    "\\tiny\n" +
    "\\Tiny\n" +
    "\\to\n" +
    "tool tips\n" +
    "\\top\n" +
    "\\triangle\n" +
    "\\triangledown\n" +
    "\\triangleleft\n" +
    "\\triangleright\n" +
    "\\trianglelefteq\n" +
    "\\trianglerighteq\n" +
    "\\triangleq\n" +
    "\\tt\n" +
    "\\twoheadleftarrow\n" +
    "\\twoheadrightarrow\n" +
    "\\ulcorner\n" +
    "\\urcorner\n" +
    "\\underbrace\n" +
    "\\underleftarrow\n" +
    "\\underrightarrow\n" +
    "\\underleftrightarrow\n" +
    "\\underline\n" +
    "\\underparen\n" +
    "\\underset\n" +
    "\\unicode\n" +
    "\\unlhd\n" +
    "\\unrhd\n" +
    "\\uparrow\n" +
    "\\Uparrow\n" +
    "\\updownarrow\n" +
    "\\Updownarrow\n" +
    "\\upharpoonleft\n" +
    "\\upharpoonright\n" +
    "\\uplus\n" +
    "\\uproot\n" +
    "\\upsilon\n" +
    "\\Upsilon\n" +
    "\\upuparrows\n" +
    "\\varDelta\n" +
    "\\varepsilon\n" +
    "\\varGamma\n" +
    "\\varinjlim\n" +
    "\\varkappa\n" +
    "\\varLambda\n" +
    "\\varlimsup\n" +
    "\\varliminf\n" +
    "\\varnothing\n" +
    "\\varOmega\n" +
    "\\varphi\n" +
    "\\varPhi\n" +
    "\\varpi\n" +
    "\\varPi\n" +
    "\\varprojlim\n" +
    "\\varpropto\n" +
    "\\varPsi\n" +
    "\\varrho\n" +
    "\\varsigma\n" +
    "\\varSigma\n" +
    "\\varsubsetneq\n" +
    "\\varsubsetneqq\n" +
    "\\varsupsetneq\n" +
    "\\varsupsetneqq\n" +
    "\\vartheta\n" +
    "\\varTheta\n" +
    "\\vartriangle\n" +
    "\\vartriangleleft\n" +
    "\\vartriangleright\n" +
    "\\varUpsilon\n" +
    "\\varXi\n" +
    "\\vcenter\n" +
    "\\vdash\n" +
    "\\Vdash\n" +
    "\\vDash\n" +
    "\\vdots\n" +
    "\\vec\n" +
    "\\vee\n" +
    "\\veebar\n" +
    "\\verb\n" +
    "\\vert\n" +
    "\\Vert\n" +
    "\\vphantom\n" +
    "\\Vvdash\n" +
    "\\wedge\n" +
    "\\widehat\n" +
    "\\widetilde\n" +
    "\\wp\n" +
    "\\wr\n" +
    "\\Xi\n" +
    "\\xi\n" +
    "\\xleftarrow\n" +
    "\\xrightarrow\n" +
    "\\yen\n" +
    "\\zeta\n" +
    "align\n" +
    "align*\n" +
    "alignat\n" +
    "alignat*\n" +
    "array\n" +
    "Bmatrix\n" +
    "bmatrix\n" +
    "cases\n" +
    "eqnarray\n" +
    "eqnarray*\n" +
    "equation\n" +
    "equation*\n" +
    "gather\n" +
    "gather*\n" +
    "matrix\n" +
    "pmatrix\n" +
    "smallmatrix\n" +
    "subarray\n" +
    "Vmatrix\n" +
    "vmatrix"